services:
  - type: web
    name: whiteboard-app
    env: node
    buildCommand: bash -c "mkdir -p /opt/render/project/src && cp src/package.json /opt/render/project/src/ && npm install && cd client && npm install && npm run build && cd .."
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        fromService:
          name: whiteboard-app
          type: web
          property: url
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false